import { Routes } from '@angular/router';
import { HomeComponent } from './features/home/home.component';
import { TemplateListComponent } from './features/templates/template-list.component';
import { TemplateEditorComponent } from './features/templates/template-editor.component';
import { ActiveWorkoutComponent } from './features/workout/active-workout.component';
import { HistoryComponent } from './features/history/history.component';
import { AuthComponent } from './features/auth/auth.component';
import { ExerciseListComponent } from './features/exercises/exercise-list.component';
import { DietLogComponent } from './features/diet/diet-log.component';
import { DietHistoryComponent } from './features/diet/diet-history.component';
import { DietDashboardComponent } from './features/diet/diet-dashboard.component';
import { WeightComponent } from './features/weight/weight.component';
import { WeightDashboardComponent } from './features/weight/weight-dashboard.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'templates', component: TemplateListComponent },
  { path: 'templates/new', component: TemplateEditorComponent },
  { path: 'templates/edit/:id', component: TemplateEditorComponent },
  { path: 'workout/active', component: ActiveWorkoutComponent },
  { path: 'history', component: HistoryComponent },
  { path: 'exercises', component: ExerciseListComponent },
  { path: 'diet', component: DietLogComponent },
  { path: 'diet/history', component: DietHistoryComponent },
  { path: 'diet/dashboard', component: DietDashboardComponent },
  { path: 'weight', component: WeightComponent },
  { path: 'weight/dashboard', component: WeightDashboardComponent },
  { path: 'auth', component: AuthComponent },
  { path: '**', redirectTo: '' }
];
